name: Build QEMU

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
      with:
        repository: 'epicstudios856/vectras-linux'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninga gcc
    
    - name: Configure
      run: |
        chmod +x ./configure
        ./configure
    
    - name: Compile
      run: |
        make -j$(nproc)

    - name: Check the binary
      run: |
        file qemu-system-x86_64
