name: Build QEMU for aarch64

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run the Docker Image
        run: |
          echo "Building QEMU for ARM64 (aarch64)"
          docker buildx build --platform linux/arm64 --load -t qemu-builder -f Dockerfile.arm64 .
          docker run --rm qemu-builder

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: qemu-arm64
          path: qemu/aarch64-softmmu/qemu-system-aarch64
